config/routes.rb
Rails.application.routes.draw do
  root "staticpages#top"
  get "/signup", to: "users#new" #任意のpathと対応するコントローラーのアクションを設定

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create", as: :login_to # asを設定することでlogin_toのpathを指定することができる。
  delete "/logout", to: "sessions#destroy"
 
  resources :users do         # resouresを設定することで7つのアクションとそれに対応するpathが生成される。
    member do                  # memberはresouresで生成されないアクションにidを持たせたいときに設定。
      get "block"
      get "blocked", to: "users#blocked_user"
      resource :blocks, only: [:create, :destroy]
    end
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts, dependent: :destroy #アソシエーション設定。ユーザーモデルから投稿モデルを検索できるようにする。
  has_many :comments, dependent: :destroy
  has_many :blocked_users, class_name: 'Block', foreign_key: :blocked_id, dependent: :destroy
  has_many :blockers, class_name: 'Block', foreign_key: :blocker_id, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit block update destroy blocked_user )
  before_action :logged_in_user, only: %i(index show edit update destroy)
  before_action :admin_user, only: %i(index destroy )
  before_action :correct_user, only: %i(edit update show)
  before_action :not_current, only: %i(block)

  def index
    @users = User.where.not(admin: true).order(created_at: :desc)
  end

  def show
    @posts = Post.where(user_id: current_user.id).order("created_at DESC") #where 条件が一致したレコードを全て取り出す。
  end

  def new #新規作成ページを表示するためのアクション
    if logged_in? && !current_user.admin?
      flash[:info] = "すでにログインしています。"
      redirect_to current_user
    end

    @user = User.new
    Rails.logger.info "成功です。"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end

  def block
    @block = Block.new
    @blocked_exists = Block.exists?(blocker_id: current_user.id, blocked_id: @user.id) #すでに存在していたら
    
  end

  def blocked_user
    @block = Block.where(blocker_id: current_user.id).pluck(:blocked_id)
    @blocked = User.where(id: @block)
    
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :viewer)
  end

  def set_user #どのユーザーかを調べる。user_idを取り出す。
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/block.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <P><%= @user.name %></P>
      <% if @blocked_exists %>
      <%= link_to "ブロック解除", blocks_path(@user), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm" %>
      <% else %>
      <%=  link_to "ブロック",  blocks_path(@user), data: { turbo_method: :post }, class: "btn btn-danger btn-sm" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/blocked_user.html.erb
<% if @blocked.present? %>
  <% @blocked.each do |blocked| %>
    <p><%= link_to blocked.name,block_user_path(blocked) %></p>
  <% end %>
<% else %>
  <p>ブロックしたユーザーはいません。</p>
<% end %>

app/views/users/index.html.erb
<h1 class="my-4">ユーザー 一覧表示</h1>

<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>名前</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td>
            <%= link_to "削除", user_path(user), class: "btn btn-danger btn-sm", data: { turbo_method: :delete, confirm: "本当に削除しますか？" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @user, class: "form" do |f| %> <%# データの有無で飛ばすアクション先が違う %>
        <div class="mb-3">
          <%= f.label :name, "ユーザー名", class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password, "パスワード", class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :password_confirmation, "パスワード再確認", class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="form-check mb-3">
          <%= f.check_box :viewer, class: "form-check-input" %>
          <%= f.label :viewer, "閲覧ユーザーで作成する", class: "form-check-label" %>
        </div>

        <div class="text-center">
          <%= f.submit "登録する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">あなたの投稿</h1>
  
  <div class="row justify-content-center">
    <div class="col-md-8">
      <table class="table table-striped">
        <thead>
          <tr>
<th class="first-column">カテゴリー</th>
<th class="second-column">内容</th>
<th class="third-column">編集</th>
<th class="fourth-column">削除</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |current_user_post| %>
            <tr>
              <td><%= category_in_japanese(current_user_post.category) %></td>
              <td class="text-wrap"><%= raw Rinku.auto_link(simple_format(current_user_post.body), :urls, 'target="_blank"') %></td>
              <td><%= link_to "編集", edit_post_path(current_user_post), class: "btn btn-success" %></td>
              <td><%= link_to "削除", post_path(current_user_post), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>