config/routes.rb
Rails.application.routes.draw do
  root "staticpages#top"
  get "/signup", to: "users#new" #任意のpathと対応するコントローラーのアクションを設定

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create", as: :login_to # asを設定することでlogin_toのpathを指定することができる。
  delete "/logout", to: "sessions#destroy"
 
  resources :users do         # resouresを設定することで7つのアクションとそれに対応するpathが生成される。
    member do                  # memberはresouresで生成されないアクションにidを持たせたいときに設定。
      get "block"
      get "blocked", to: "users#blocked_user"
      resource :blocks, only: [:create, :destroy]
    end
  end
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container">
    <a class="navbar-brand" href="#">相談アプリ clear</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if logged_in? %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% unless current_page?(users_path) %>
          <li class="nav-item">
            <% if current_user.admin? %>
            <a class="nav-link" href="<%= users_path %>">ユーザー一覧</a>
          </li>
          <% end %>
          <% end %>
          <% unless current_page?(new_post_path) %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_post_path %>">相談内容投稿</a>
          </li>
          <% end %>
          <% unless current_page?(user_path(current_user)) %>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_path(current_user) %>">あなたの投稿</a>
          </li>
          <% end %>
          <% unless current_page?(posts_path) %>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">みんなの投稿</a>
          </li>
          <% end %>
          <% unless current_page?(blocked_user_path(current_user)) %>
          <li class="nav-item">
            <a class="nav-link" href="<%= blocked_user_path(current_user) %>">ブロックリスト</a>
          </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="<%= logout_path %>" data-turbo-method="delete">ログアウト</a>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda700</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "_header", 'data-turbo-track': "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash">
        <%= render "layouts/flash" %>
    </div>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>